// Static question library organized by grade level.
// Each question: { passage (optional), question, options, correct_index, explanation }

const Q = {
  // ─── GRADE 1 (Forest Zone) ───────────────────────────────────────────
  grade1: [
    {
      question: 'Which word is a sight word you should know?',
      options: ['the', 'xylophone', 'dinosaur', 'umbrella'],
      correct_index: 0,
      explanation: '"The" is one of the most common sight words in English.',
    },
    {
      question: 'What does the word "big" mean?',
      options: ['Small and tiny', 'Large in size', 'Fast and quick', 'Soft and quiet'],
      correct_index: 1,
      explanation: '"Big" means large in size.',
    },
    {
      passage: 'The cat sat on the mat. It was a fat cat. The cat was happy.',
      question: 'Where did the cat sit?',
      options: ['On a chair', 'On the mat', 'On a bed', 'In the tree'],
      correct_index: 1,
      explanation: 'The passage says "The cat sat on the mat."',
    },
    {
      question: 'Which word rhymes with "cat"?',
      options: ['dog', 'hat', 'cup', 'fish'],
      correct_index: 1,
      explanation: '"Hat" rhymes with "cat" — both end in the "-at" sound.',
    },
    {
      passage: 'Dan has a red ball. He likes to play with it after school.',
      question: 'What color is Dan\'s ball?',
      options: ['Blue', 'Green', 'Red', 'Yellow'],
      correct_index: 2,
      explanation: 'The passage says "Dan has a red ball."',
    },
    {
      question: 'Which sentence is written correctly?',
      options: ['the dog runs fast.', 'The dog runs fast.', 'the Dog runs fast.', 'The Dog Runs Fast.'],
      correct_index: 1,
      explanation: 'A sentence starts with a capital letter and ends with a period.',
    },
    {
      passage: 'Mom baked a cake. It smelled so good. We ate it for dinner.',
      question: 'What did Mom bake?',
      options: ['Bread', 'Pie', 'Cake', 'Cookies'],
      correct_index: 2,
      explanation: 'The passage says "Mom baked a cake."',
    },
    {
      question: 'What is the opposite of "hot"?',
      options: ['Warm', 'Cold', 'Big', 'Fast'],
      correct_index: 1,
      explanation: '"Cold" is the opposite of "hot."',
    },
    {
      question: 'How many syllables are in the word "butterfly"?',
      options: ['1', '2', '3', '4'],
      correct_index: 2,
      explanation: '"Butterfly" has 3 syllables: but-ter-fly.',
    },
    {
      passage: 'Sam saw a bird in the tree. The bird sang a song. Sam liked the song.',
      question: 'What did the bird do in the tree?',
      options: ['Ate food', 'Built a nest', 'Sang a song', 'Flew away'],
      correct_index: 2,
      explanation: 'The passage says "The bird sang a song."',
    },
    {
      question: 'Which word means "to look at something carefully"?',
      options: ['run', 'sleep', 'look', 'jump'],
      correct_index: 2,
      explanation: '"Look" means to direct your eyes at something.',
    },
    {
      question: 'Which of these is a complete sentence?',
      options: ['The big dog.', 'Runs fast.', 'The big dog runs fast.', 'Big dog fast.'],
      correct_index: 2,
      explanation: 'A complete sentence has a subject and a verb.',
    },
    {
      passage: 'It was a sunny day. Tom went to the park. He played on the swings.',
      question: 'What did Tom do at the park?',
      options: ['Read a book', 'Played on the swings', 'Fed the ducks', 'Rode a bike'],
      correct_index: 1,
      explanation: 'The passage says "He played on the swings."',
    },
    {
      question: 'What punctuation goes at the end of a question?',
      options: ['.', '!', '?', ','],
      correct_index: 2,
      explanation: 'A question ends with a question mark (?).',
    },
    {
      question: 'Which word is an action word (verb)?',
      options: ['happy', 'blue', 'jump', 'ball'],
      correct_index: 2,
      explanation: '"Jump" is a verb — it describes an action.',
    },
    {
      passage: 'Lily has a pet fish. The fish is orange. It lives in a bowl.',
      question: 'What color is Lily\'s fish?',
      options: ['Blue', 'Orange', 'Green', 'Red'],
      correct_index: 1,
      explanation: 'The passage says "The fish is orange."',
    },
    {
      question: 'What is the beginning sound in the word "frog"?',
      options: ['r', 'o', 'f', 'g'],
      correct_index: 2,
      explanation: '"Frog" starts with the letter F.',
    },
    {
      question: 'Which word is a naming word (noun)?',
      options: ['run', 'quickly', 'apple', 'bright'],
      correct_index: 2,
      explanation: '"Apple" is a noun — it names a thing.',
    },
    {
      passage: 'Max was tired. He went to bed early. In the morning he felt better.',
      question: 'Why did Max go to bed early?',
      options: ['He was hungry', 'He was tired', 'It was late', 'He was sick'],
      correct_index: 1,
      explanation: 'The passage says "Max was tired."',
    },
    {
      question: 'Which word has the short "a" sound like in "cat"?',
      options: ['cake', 'rain', 'hat', 'day'],
      correct_index: 2,
      explanation: '"Hat" has the short "a" sound, just like "cat."',
    },
  ],

  // ─── GRADE 2 (no dedicated zone but used for mixed) ──────────────────
  grade2: [
    {
      passage: 'Frogs start their life as eggs in the water. Then they become tadpoles. Finally, they grow legs and become frogs.',
      question: 'What is the main idea of this passage?',
      options: ['Frogs can jump high', 'Frogs live in ponds', 'Frogs go through stages as they grow', 'Tadpoles eat plants'],
      correct_index: 2,
      explanation: 'The passage is mostly about the life stages of a frog.',
    },
    {
      question: 'Who is usually the most important person in a story?',
      options: ['The setting', 'The main character', 'The author', 'The narrator'],
      correct_index: 1,
      explanation: 'The main character is usually the most important person in a story.',
    },
    {
      passage: 'Rosa woke up late. She rushed to get dressed and ran to school. She was out of breath when she arrived.',
      question: 'Why was Rosa out of breath?',
      options: ['She was sick', 'She ran to school', 'She forgot her lunch', 'She was nervous'],
      correct_index: 1,
      explanation: 'The passage says she "ran to school," which made her out of breath.',
    },
    {
      question: 'What does "fluency" mean when reading?',
      options: ['Reading slowly word by word', 'Reading smoothly and at a good pace', 'Reading very quietly', 'Skipping hard words'],
      correct_index: 1,
      explanation: 'Reading fluency means reading smoothly, accurately, and at a good pace.',
    },
    {
      passage: 'Bears sleep through winter. This is called hibernation. They eat a lot before winter to store energy.',
      question: 'What do bears do before hibernation?',
      options: ['Build a new den', 'Swim in rivers', 'Eat a lot of food', 'Travel south'],
      correct_index: 2,
      explanation: 'The passage says bears "eat a lot before winter to store energy."',
    },
    {
      question: 'Which sentence uses a describing word (adjective)?',
      options: ['The dog runs.', 'She smiled.', 'The fluffy dog runs.', 'He went home.'],
      correct_index: 2,
      explanation: '"Fluffy" is an adjective that describes the dog.',
    },
    {
      passage: 'Kim loved to draw. Every day after school, she would sit at her desk and sketch animals.',
      question: 'What does Kim do after school every day?',
      options: ['Reads books', 'Plays outside', 'Sketches animals', 'Watches TV'],
      correct_index: 2,
      explanation: 'The passage says "she would sit at her desk and sketch animals."',
    },
    {
      question: 'What is the setting of a story?',
      options: ['The problem in the story', 'The lesson of the story', 'Where and when the story takes place', 'Who the story is about'],
      correct_index: 2,
      explanation: 'The setting is where and when a story takes place.',
    },
    {
      question: 'Which word is a plural noun?',
      options: ['child', 'run', 'dogs', 'happy'],
      correct_index: 2,
      explanation: '"Dogs" is plural — it means more than one dog.',
    },
    {
      passage: 'The wind blew hard. Leaves flew off the trees. Sam pulled his coat tight and walked faster.',
      question: 'What does Sam do when the wind blows hard?',
      options: ['Goes inside', 'Pulls his coat tight', 'Climbs a tree', 'Stops walking'],
      correct_index: 1,
      explanation: 'The passage says "Sam pulled his coat tight."',
    },
    {
      question: 'What does it mean when a word is in a story\'s glossary?',
      options: ['It is a character\'s name', 'It is an important word with a definition', 'It is a spelling mistake', 'It is a place name'],
      correct_index: 1,
      explanation: 'A glossary provides definitions of important words used in the text.',
    },
    {
      question: 'Which of the following is a compound word?',
      options: ['running', 'happy', 'sunlight', 'slowly'],
      correct_index: 2,
      explanation: '"Sunlight" is a compound word made of "sun" and "light."',
    },
    {
      passage: 'Penguins cannot fly, but they are excellent swimmers. They use their wings like flippers in the water.',
      question: 'How do penguins use their wings?',
      options: ['To fly south', 'Like flippers to swim', 'To stay warm', 'To catch fish on land'],
      correct_index: 1,
      explanation: 'The passage says penguins "use their wings like flippers in the water."',
    },
    {
      question: 'A paragraph is a group of sentences that all talk about ___.',
      options: ['different ideas', 'the same main idea', 'rhyming words', 'different characters'],
      correct_index: 1,
      explanation: 'A paragraph is a group of related sentences focused on one main idea.',
    },
    {
      question: 'What does the prefix "re-" mean in the word "rewrite"?',
      options: ['Not', 'Again', 'Before', 'Under'],
      correct_index: 1,
      explanation: 'The prefix "re-" means "again," so "rewrite" means to write again.',
    },
  ],

  // ─── GRADE 3 (Mountain Zone) ─────────────────────────────────────────
  grade3: [
    {
      passage: 'Mia and Jake both loved to read. Mia preferred fantasy books with dragons and magic. Jake liked nonfiction books about space. They agreed that reading was the best hobby.',
      question: 'How are Mia and Jake similar?',
      options: ['They both like fantasy books', 'They both enjoy reading', 'They both read nonfiction', 'They both like space books'],
      correct_index: 1,
      explanation: 'Both Mia and Jake love reading — that is what they have in common.',
    },
    {
      passage: 'The volcano erupted suddenly. Hot lava poured down the mountain. Animals ran away quickly. The sky filled with gray smoke.',
      question: 'What is the best summary of this passage?',
      options: ['Animals ran away from a storm', 'A volcano erupted and caused chaos', 'The mountain was on fire', 'Smoke filled the forest'],
      correct_index: 1,
      explanation: 'The passage describes a volcanic eruption and its effects on the surroundings.',
    },
    {
      question: 'What does "compare and contrast" mean?',
      options: ['Find what happens first and last', 'Tell how two things are alike and different', 'Describe the setting and characters', 'Explain the problem and solution'],
      correct_index: 1,
      explanation: 'Compare and contrast means identifying similarities and differences between two things.',
    },
    {
      passage: 'Trees are important to the environment. They produce oxygen, provide homes for animals, and clean the air we breathe.',
      question: 'According to the passage, what is ONE thing trees do?',
      options: ['Make rain', 'Produce oxygen', 'Create rivers', 'Grow fruit'],
      correct_index: 1,
      explanation: 'The passage states that trees "produce oxygen."',
    },
    {
      question: 'What is descriptive writing?',
      options: ['Writing that tells a list of facts', 'Writing that uses details to paint a picture with words', 'Writing that argues a point', 'Writing that retells a story in order'],
      correct_index: 1,
      explanation: 'Descriptive writing uses vivid details and sensory language to help readers visualize.',
    },
    {
      passage: 'Leo forgot his umbrella on a rainy day. He got soaking wet walking home. He shivered and sneezed for the rest of the afternoon.',
      question: 'What happened because Leo forgot his umbrella?',
      options: ['He missed the bus', 'He got very wet', 'He lost his backpack', 'He stayed home from school'],
      correct_index: 1,
      explanation: 'The passage says Leo "got soaking wet" because he forgot his umbrella.',
    },
    {
      question: 'In the word "unhappy," what does the prefix "un-" mean?',
      options: ['Very', 'Not', 'Again', 'Too much'],
      correct_index: 1,
      explanation: '"Un-" means "not," so "unhappy" means not happy.',
    },
    {
      passage: 'Wolves live and hunt in groups called packs. The leader is called the alpha wolf. Pack members cooperate to chase and catch prey.',
      question: 'What is the main idea of this paragraph?',
      options: ['Wolves eat large animals', 'Wolves are dangerous', 'Wolves live and work together in packs', 'Alpha wolves are the biggest'],
      correct_index: 2,
      explanation: 'The paragraph is about how wolves live and hunt together as a group.',
    },
    {
      question: 'Which word best fits in the blank? "The runner was __ because she won the race."',
      options: ['sad', 'angry', 'elated', 'tired'],
      correct_index: 2,
      explanation: '"Elated" means very happy, which fits someone who just won a race.',
    },
    {
      question: 'What is a "summary" of a story?',
      options: ['A list of all the characters', 'A short retelling of the most important events', 'A copy of the whole story', 'A description of the setting'],
      correct_index: 1,
      explanation: 'A summary is a brief retelling of only the most important parts of a story.',
    },
    {
      passage: 'The butterfly starts as an egg, becomes a caterpillar, forms a chrysalis, and then emerges as a butterfly. This process is called metamorphosis.',
      question: 'What does "metamorphosis" mean based on the passage?',
      options: ['A type of butterfly', 'A complete change in form', 'The wings of a butterfly', 'A kind of cocoon'],
      correct_index: 1,
      explanation: 'Metamorphosis refers to the complete transformation a butterfly undergoes.',
    },
    {
      question: 'Which type of text would you read to learn facts about sharks?',
      options: ['A fiction story', 'A poem', 'An informational text', 'A fairy tale'],
      correct_index: 2,
      explanation: 'Informational (nonfiction) texts contain facts about real topics like sharks.',
    },
    {
      passage: 'Emma was nervous about her first day at a new school. She didn\'t know anyone. But when a girl named Sofia smiled at her, Emma felt a little better.',
      question: 'How does Emma feel at the beginning?',
      options: ['Excited', 'Nervous', 'Angry', 'Confused'],
      correct_index: 1,
      explanation: 'The passage says "Emma was nervous about her first day."',
    },
    {
      question: 'What is the purpose of a heading in a nonfiction text?',
      options: ['To make the page look nice', 'To tell what a section is about', 'To give the author\'s name', 'To list vocabulary words'],
      correct_index: 1,
      explanation: 'Headings tell readers what topic a section of text will cover.',
    },
    {
      question: 'What does the word "ancient" mean?',
      options: ['Very new', 'Very old', 'Very large', 'Very fast'],
      correct_index: 1,
      explanation: '"Ancient" means very old, usually thousands of years ago.',
    },
  ],

  // ─── GRADE 4 (Ocean Zone) ────────────────────────────────────────────
  grade4: [
    {
      passage: 'Amara worked hard every day, practicing violin for hours. Even when her fingers hurt, she kept playing. She believed that effort matters more than talent.',
      question: 'What is the theme of this passage?',
      options: ['Music is the best hobby', 'Hard work leads to success', 'Talent is all you need', 'Practice makes you tired'],
      correct_index: 1,
      explanation: 'The theme is that persistent effort matters more than natural talent.',
    },
    {
      passage: 'The ancient Egyptians built enormous pyramids as tombs for their pharaohs. These structures required thousands of workers and many years to complete.',
      question: 'What does "enormous" mean as used in this passage?',
      options: ['Very old', 'Very colorful', 'Very large', 'Very dangerous'],
      correct_index: 2,
      explanation: 'Context clues show the pyramids required thousands of workers — suggesting they were huge.',
    },
    {
      question: 'What is the difference between a character\'s "traits" and "feelings"?',
      options: ['Traits are temporary; feelings are permanent', 'Traits are lasting qualities; feelings change with events', 'They mean the same thing', 'Traits are physical; feelings are imaginary'],
      correct_index: 1,
      explanation: 'Traits are lasting personality qualities; feelings are emotional responses to events.',
    },
    {
      passage: 'First, the author introduces the setting. Then the characters face a conflict. Finally, the conflict is resolved.',
      question: 'This passage describes which literary element?',
      options: ['Point of view', 'Mood', 'Plot structure', 'Theme'],
      correct_index: 2,
      explanation: 'Plot structure refers to how a story is organized: introduction, conflict, and resolution.',
    },
    {
      question: 'In an opinion essay, what is the most important part of the opening paragraph?',
      options: ['A funny story', 'The author\'s opinion statement', 'A list of facts', 'A description of the setting'],
      correct_index: 1,
      explanation: 'An opinion essay opens by clearly stating the author\'s opinion or position.',
    },
    {
      passage: 'Despite being small, the hummingbird can fly forward, backward, and even hover in place. Its wings beat up to 80 times per second.',
      question: 'What conclusion can you draw about hummingbirds from this passage?',
      options: ['They are slow flyers', 'They are remarkable fliers', 'They only fly forward', 'They have large wings'],
      correct_index: 1,
      explanation: 'Their unique flying abilities and rapid wingbeats show they are exceptional fliers.',
    },
    {
      question: 'What is the purpose of a "topic sentence" in a paragraph?',
      options: ['To end the paragraph', 'To introduce what the paragraph is about', 'To provide an example', 'To list details'],
      correct_index: 1,
      explanation: 'The topic sentence states the main idea that the rest of the paragraph supports.',
    },
    {
      passage: 'The explorers were exhausted after three weeks in the jungle. Their supplies were running low, and the path ahead was unclear.',
      question: 'Which word best describes the mood of this passage?',
      options: ['Cheerful', 'Tense and uncertain', 'Peaceful', 'Exciting'],
      correct_index: 1,
      explanation: 'Words like "exhausted," "running low," and "unclear path" create a tense, uncertain mood.',
    },
    {
      question: 'What are "context clues"?',
      options: ['Pictures in a book', 'Information near an unknown word that helps you understand its meaning', 'The chapter titles', 'Words in bold print'],
      correct_index: 1,
      explanation: 'Context clues are hints in the surrounding text that help readers figure out unfamiliar words.',
    },
    {
      question: 'Which sentence is an opinion?',
      options: ['Earth has one moon.', 'Dogs make the best pets.', 'The Amazon is a large river.', 'Whales are mammals.'],
      correct_index: 1,
      explanation: '"Dogs make the best pets" is an opinion — it cannot be proven as fact.',
    },
    {
      passage: 'Maya loved soccer. She practiced every day after school. Her coach said she had potential to play at a higher level.',
      question: 'What does "potential" mean as used here?',
      options: ['A mistake', 'Natural ability that can grow', 'A type of award', 'A kind of practice'],
      correct_index: 1,
      explanation: '"Potential" means the capacity to develop into something in the future.',
    },
    {
      question: 'What is the purpose of a conclusion in an essay?',
      options: ['To introduce a new idea', 'To list all the facts', 'To wrap up and restate the main idea', 'To tell a funny story'],
      correct_index: 2,
      explanation: 'A conclusion wraps up the essay and restates the main idea in new words.',
    },
    {
      passage: 'After the storm, the streets were flooded and trees had fallen across the road. The town came together to clean up.',
      question: 'What happened after the storm?',
      options: ['People left the town', 'Streets flooded and the town helped clean up', 'Nothing was damaged', 'The power was restored'],
      correct_index: 1,
      explanation: 'The passage says streets were flooded and the community worked to clean up.',
    },
    {
      question: 'What does it mean to "summarize" a text?',
      options: ['Copy the text word for word', 'Share only the most important ideas in your own words', 'Add your own opinion', 'List every detail in order'],
      correct_index: 1,
      explanation: 'A summary briefly retells only the key information in your own words.',
    },
    {
      question: 'Which sentence uses correct subject-verb agreement?',
      options: ['The dogs runs fast.', 'She run every morning.', 'The children are playing.', 'He go to school.'],
      correct_index: 2,
      explanation: '"The children are playing" correctly matches the plural subject with the plural verb.',
    },
  ],

  // ─── GRADE 5 (Desert Zone) ───────────────────────────────────────────
  grade5: [
    {
      passage: 'Even though Marcus never said he was sad, he stopped eating lunch with his friends and spent recess alone on the bench.',
      question: 'What can you infer about Marcus?',
      options: ['He is excited about something', 'He is probably feeling sad or upset', 'He is practicing being alone', 'He is preparing for a test'],
      correct_index: 1,
      explanation: 'His behavior — avoiding friends and sitting alone — suggests he is upset even though he doesn\'t say so.',
    },
    {
      passage: 'Plastic waste in the ocean kills over a million seabirds each year. Marine mammals mistake plastic bags for food. Scientists urge immediate action.',
      question: 'Which detail best supports the argument that ocean plastic is a serious problem?',
      options: ['Scientists are studying the ocean', 'Plastic is made from oil', 'Over a million seabirds die from plastic each year', 'Bags float on water'],
      correct_index: 2,
      explanation: 'The statistic about seabird deaths directly supports the claim that ocean plastic is dangerous.',
    },
    {
      question: 'What is the difference between a "theme" and a "main idea"?',
      options: ['They are the same thing', 'Theme is a life lesson; main idea is what a text is specifically about', 'Main idea is the moral; theme is the plot', 'Theme is for poems only'],
      correct_index: 1,
      explanation: 'Theme is a broader life lesson; main idea is the specific focus of a passage.',
    },
    {
      passage: 'The Great Wall of China stretches over 13,000 miles. It was built to protect China from invasions. Millions of workers spent decades constructing it.',
      question: 'What was the purpose of building the Great Wall of China?',
      options: ['To create a tourist attraction', 'To protect China from invasions', 'To mark the border of China', 'To provide jobs for workers'],
      correct_index: 1,
      explanation: 'The passage states it "was built to protect China from invasions."',
    },
    {
      question: 'In an essay, what is the role of body paragraphs?',
      options: ['To introduce the topic', 'To wrap up the essay', 'To provide evidence and support for the thesis', 'To tell a personal story'],
      correct_index: 2,
      explanation: 'Body paragraphs present evidence and details that support the essay\'s main argument.',
    },
    {
      passage: 'Although solar energy is clean and renewable, its main drawback is that it requires consistent sunlight, making it less effective in cloudy regions.',
      question: 'What is one weakness of solar energy according to the passage?',
      options: ['It is expensive to produce', 'It creates pollution', 'It needs consistent sunlight to work well', 'It requires a lot of land'],
      correct_index: 2,
      explanation: 'The passage says solar energy is "less effective in cloudy regions" due to inconsistent sunlight.',
    },
    {
      question: 'What does it mean to "cite evidence" from a text?',
      options: ['Make up an example', 'Copy the whole passage', 'Use specific details from the text to support your point', 'Summarize the author\'s life'],
      correct_index: 2,
      explanation: 'Citing evidence means referencing specific parts of the text to back up your claim.',
    },
    {
      passage: 'Zara had always been afraid of the dark. But when the lights went out during the storm, she remembered her father\'s words: "Courage isn\'t the absence of fear — it\'s acting despite it." She got up and found the candles.',
      question: 'What can you infer about Zara\'s character?',
      options: ['She is reckless', 'She overcomes her fear by acting bravely', 'She forgets she is afraid', 'She waits for someone to help her'],
      correct_index: 1,
      explanation: 'Despite her fear, Zara remembers advice about courage and acts — showing she is brave.',
    },
    {
      question: 'What is the purpose of a "thesis statement"?',
      options: ['To list facts about a topic', 'To state the central argument of an essay', 'To summarize a book', 'To describe the setting'],
      correct_index: 1,
      explanation: 'A thesis statement clearly states the main argument or point of an essay.',
    },
    {
      question: 'What is a "figurative language" device where you compare two things using "like" or "as"?',
      options: ['Metaphor', 'Simile', 'Alliteration', 'Hyperbole'],
      correct_index: 1,
      explanation: 'A simile compares two things using "like" or "as" (e.g., "fast as lightning").',
    },
    {
      passage: 'Doctors now recommend limiting screen time for children because excessive use has been linked to sleep problems and reduced attention spans.',
      question: 'What conclusion is supported by this passage?',
      options: ['Screen time helps children focus', 'Too much screen time can negatively affect children\'s health', 'Doctors don\'t understand technology', 'Sleep problems are rare'],
      correct_index: 1,
      explanation: 'The passage links excessive screen time to sleep problems and reduced attention spans.',
    },
    {
      question: 'When a writer uses "point of view," what does that mean?',
      options: ['Where the story takes place', 'The perspective from which the story is told', 'The theme of the story', 'The problem in the story'],
      correct_index: 1,
      explanation: 'Point of view refers to who is narrating the story — first, second, or third person.',
    },
    {
      question: 'What is a "primary source"?',
      options: ['A textbook chapter', 'A firsthand account or original document from the time period', 'A summary written by a historian', 'A fictional story based on true events'],
      correct_index: 1,
      explanation: 'A primary source is an original document or firsthand account (diary, letter, photograph).',
    },
    {
      passage: 'Rainforests cover only 6% of Earth\'s surface but are home to over half of the world\'s plant and animal species.',
      question: 'What makes this fact surprising?',
      options: ['Rainforests are very common', 'A small area of land contains an enormous amount of biodiversity', 'Half of Earth is covered by rainforests', 'Animals prefer open land'],
      correct_index: 1,
      explanation: 'It is remarkable that such a small percentage of Earth\'s surface hosts more than half of all species.',
    },
    {
      question: 'What is the difference between "explicit" and "implicit" information in a text?',
      options: ['Explicit is hidden; implicit is stated directly', 'Explicit is stated directly; implicit must be inferred', 'They mean the same thing', 'Explicit is opinion; implicit is fact'],
      correct_index: 1,
      explanation: 'Explicit information is directly stated; implicit information must be inferred from clues.',
    },
  ],

  // ─── GRADE 6 (Ice Zone) ──────────────────────────────────────────────
  grade6: [
    {
      passage: 'Throughout the novel, the protagonist\'s journey from a fearful child to a confident leader mirrors the broader social change happening in the town around her.',
      question: 'From whose point of view is this story most likely told?',
      options: ['Third-person omniscient', 'Second person', 'First person from the protagonist\'s perspective', 'Third-person limited following the protagonist'],
      correct_index: 3,
      explanation: 'The focus on the protagonist\'s internal journey suggests a third-person limited perspective.',
    },
    {
      passage: 'The author argues that homework should be abolished. She provides three studies showing students who do less homework perform equally well on tests.',
      question: 'Which sentence best describes the author\'s purpose?',
      options: ['To entertain readers with a funny story', 'To persuade readers that homework is unnecessary', 'To inform readers about study habits', 'To describe a student\'s daily routine'],
      correct_index: 1,
      explanation: 'The author uses studies to build a persuasive argument against homework.',
    },
    {
      question: 'What is "literary analysis"?',
      options: ['Retelling a story in order', 'Closely examining how and why an author makes specific choices', 'Writing a new story in a similar style', 'Listing all characters and events'],
      correct_index: 1,
      explanation: 'Literary analysis means examining an author\'s choices — word choice, structure, themes — and their effects.',
    },
    {
      passage: '"I have a dream," the speaker repeated throughout his speech, building emotion with each repetition.',
      question: 'What literary device is the speaker using?',
      options: ['Simile', 'Anaphora', 'Metaphor', 'Irony'],
      correct_index: 1,
      explanation: 'Anaphora is the repetition of a phrase at the beginning of successive sentences for emphasis.',
    },
    {
      question: 'In persuasive writing, what is a "counterargument"?',
      options: ['Your main opinion', 'A supporting detail', 'An opposing viewpoint that you then address or refute', 'The conclusion of your essay'],
      correct_index: 2,
      explanation: 'A counterargument presents the opposing side, which a strong writer then addresses or disproves.',
    },
    {
      passage: 'The factory had been silent for years. Weeds pushed through the cracked concrete. Rust covered the old machines.',
      question: 'What is the mood created by this passage?',
      options: ['Cheerful and hopeful', 'Mysterious and exciting', 'Abandoned and melancholy', 'Peaceful and calm'],
      correct_index: 2,
      explanation: 'Details like silence, weeds, and rust create a mood of abandonment and sadness.',
    },
    {
      question: 'What does it mean when a text has a "biased" point of view?',
      options: ['The text is accurate and balanced', 'The text unfairly favors one side', 'The text uses difficult vocabulary', 'The text is written in first person'],
      correct_index: 1,
      explanation: 'A biased text favors one perspective and may leave out important opposing information.',
    },
    {
      passage: 'Social media allows people to connect globally, but critics argue it has increased anxiety and decreased face-to-face communication among teens.',
      question: 'Which sentence best represents a text that "cites evidence"?',
      options: ['Social media is bad.', 'I think social media causes problems.', 'Critics argue social media has increased anxiety among teens.', 'Everyone uses social media.'],
      correct_index: 2,
      explanation: 'Citing a specific claim from critics is an example of using evidence rather than opinion.',
    },
    {
      question: 'What is the difference between "tone" and "mood" in a literary text?',
      options: ['They are the same thing', 'Tone is the author\'s attitude; mood is the reader\'s emotional response', 'Mood is the author\'s attitude; tone is the reader\'s response', 'Tone is the topic; mood is the theme'],
      correct_index: 1,
      explanation: 'Tone reflects the author\'s attitude toward the subject; mood is the atmosphere felt by the reader.',
    },
    {
      question: 'What is the purpose of using "text evidence" in a literary response?',
      options: ['To make your essay longer', 'To support your argument with specific details from the text', 'To quote every sentence in the passage', 'To describe the author\'s life'],
      correct_index: 1,
      explanation: 'Text evidence grounds your argument in specific details from the actual text.',
    },
    {
      passage: 'Despite his cheerful smile and constant jokes, Elliot felt deeply lonely. Nobody knew the sadness behind his laughter.',
      question: 'What literary technique does this passage use?',
      options: ['Foreshadowing', 'Dramatic irony', 'Alliteration', 'Flashback'],
      correct_index: 1,
      explanation: 'Dramatic irony occurs when readers know something (his loneliness) that other characters do not.',
    },
    {
      question: 'What makes an argument "credible"?',
      options: ['It uses emotional language', 'It is supported by reliable evidence and logical reasoning', 'It is very long and detailed', 'It is written in first person'],
      correct_index: 1,
      explanation: 'Credibility comes from reliable evidence, logical reasoning, and trustworthy sources.',
    },
    {
      passage: 'The storm arrived without warning. Within hours, entire neighborhoods were underwater.',
      question: 'What can you infer about the storm\'s intensity?',
      options: ['It was a light drizzle', 'It was extremely powerful and destructive', 'It lasted only a few minutes', 'It was expected by residents'],
      correct_index: 1,
      explanation: 'Flooding entire neighborhoods without warning suggests the storm was catastrophically powerful.',
    },
    {
      question: 'What is the purpose of "revision" in the writing process?',
      options: ['To check for spelling errors only', 'To reconsider and improve ideas, structure, and clarity', 'To write a first draft', 'To publish the final essay'],
      correct_index: 1,
      explanation: 'Revision involves rethinking ideas, organization, and clarity — not just fixing surface errors.',
    },
    {
      question: 'Which of the following is an example of a "metaphor"?',
      options: ['Her smile was like sunshine.', 'Life is a journey.', 'The wind howled loudly.', 'She ran as fast as a cheetah.'],
      correct_index: 1,
      explanation: '"Life is a journey" directly equates two things without using "like" or "as" — that is a metaphor.',
    },
  ],

  // ─── GRADE 7 (Storm/Drylands Zone) ──────────────────────────────────
  grade7: [
    {
      passage: 'In the story, the crumbling mansion represents the family\'s fading power and pride. Each broken window and peeling wall reflects another secret buried for decades.',
      question: 'What does the crumbling mansion most likely symbolize?',
      options: ['The family\'s wealth', 'The family\'s declining status and hidden secrets', 'The harsh weather in the region', 'The main character\'s fear of old buildings'],
      correct_index: 1,
      explanation: 'The mansion\'s physical decay mirrors the family\'s hidden problems and loss of status — classic symbolism.',
    },
    {
      passage: 'Proponents of year-round schooling argue it prevents learning loss over summer. Opponents counter that students need rest and that family schedules would be disrupted.',
      question: 'What is the tone of this passage?',
      options: ['Strongly in favor of year-round school', 'Strongly opposed to year-round school', 'Balanced and informational', 'Sarcastic and dismissive'],
      correct_index: 2,
      explanation: 'The passage presents both sides fairly, indicating a balanced, informational tone.',
    },
    {
      question: 'What is an "argumentative essay"?',
      options: ['An essay that tells a personal story', 'An essay that takes a clear position and supports it with evidence', 'An essay that describes a place or person', 'An essay that summarizes a book'],
      correct_index: 1,
      explanation: 'An argumentative essay defends a specific claim using evidence and logical reasoning.',
    },
    {
      passage: 'The author writes: "We pour chemicals into the sky every second, yet we act surprised when the climate changes." The word "pour" is intentional.',
      question: 'What effect does the word "pour" create?',
      options: ['It suggests pollution is harmless', 'It emphasizes the massive and constant scale of chemical emissions', 'It implies chemicals are liquid', 'It minimizes the problem'],
      correct_index: 1,
      explanation: '"Pour" implies a large, continuous flow — emphasizing the scale and persistence of emissions.',
    },
    {
      question: 'What is the difference between "mood" and "atmosphere" in literature?',
      options: ['They are unrelated concepts', 'Both refer to the emotional feeling created by a text; atmosphere often refers to the setting\'s contribution', 'Mood is for poetry; atmosphere is for novels', 'Atmosphere is the author\'s attitude; mood is the setting'],
      correct_index: 1,
      explanation: 'Mood and atmosphere both describe emotional tone; atmosphere specifically relates to the setting\'s feel.',
    },
    {
      passage: 'The researcher found that students who read for pleasure score significantly higher on standardized tests than those who do not.',
      question: 'Which is the strongest evidence to support an essay about the benefits of reading?',
      options: ['Reading is a fun activity for all ages.', 'Some people enjoy reading more than watching TV.', 'Students who read for pleasure score significantly higher on standardized tests.', 'Libraries have many books available.'],
      correct_index: 2,
      explanation: 'A specific, measurable statistic linking reading to test scores is the strongest evidence.',
    },
    {
      question: 'What is a "rhetorical question"?',
      options: ['A question with no answer', 'A question asked for effect, not expecting a literal answer', 'A question at the end of an essay', 'A question that compares two things'],
      correct_index: 1,
      explanation: 'A rhetorical question is posed to make a point or provoke thought, not to receive an answer.',
    },
    {
      passage: 'At age twelve, he composed his first symphony. Critics dismissed it as the work of a child prodigy who would fade. Decades later, his music is still performed worldwide.',
      question: 'What can you infer from this passage?',
      options: ['The critics were right about him', 'He overcame early skepticism to achieve lasting success', 'He stopped composing music after childhood', 'His music was never accepted by critics'],
      correct_index: 1,
      explanation: 'Despite early dismissal, his music remains celebrated — showing he succeeded beyond the critics\' predictions.',
    },
    {
      question: 'What is the purpose of a "hook" at the start of an essay?',
      options: ['To state the thesis immediately', 'To grab the reader\'s attention and make them want to keep reading', 'To list all supporting details', 'To summarize the essay'],
      correct_index: 1,
      explanation: 'A hook is an engaging opening — a question, quote, or surprising fact — that draws readers in.',
    },
    {
      question: 'What does "connotation" mean?',
      options: ['The dictionary definition of a word', 'The emotional or cultural association a word carries beyond its literal meaning', 'The origin or history of a word', 'The plural form of a word'],
      correct_index: 1,
      explanation: 'Connotation is the implied meaning or feeling a word suggests beyond its strict definition.',
    },
    {
      passage: 'The government has a responsibility to protect the environment. Without clean air, water, and soil, no economy can survive long-term.',
      question: 'What type of appeal does the writer use when mentioning the economy?',
      options: ['Appeal to emotion', 'Appeal to logic (logos)', 'Appeal to authority', 'Appeal to tradition'],
      correct_index: 1,
      explanation: 'Citing economic consequences is a logical appeal (logos) based on practical reasoning.',
    },
    {
      question: 'What is "allusion" as a literary device?',
      options: ['A trick played on the reader', 'A reference to a well-known person, place, event, or text', 'A figure of speech using exaggeration', 'A type of rhyme scheme'],
      correct_index: 1,
      explanation: 'An allusion is an indirect reference to another work, historical event, or cultural figure.',
    },
    {
      passage: 'As night fell, the city lights came on like stars scattered across the valley floor.',
      question: 'What literary device is used in this sentence?',
      options: ['Personification', 'Hyperbole', 'Simile', 'Symbolism'],
      correct_index: 2,
      explanation: 'City lights are compared to stars using "like" — making this a simile.',
    },
    {
      question: 'What is the purpose of a "transition" in writing?',
      options: ['To end the essay', 'To introduce the first idea', 'To connect ideas and help writing flow smoothly', 'To define vocabulary words'],
      correct_index: 2,
      explanation: 'Transitions link ideas between sentences and paragraphs, improving the flow of writing.',
    },
    {
      question: 'What does "synthesize" mean when working with multiple sources?',
      options: ['Copy information from each source', 'Combine ideas from different sources to form a new understanding', 'Summarize one source at a time', 'Cite sources in a bibliography'],
      correct_index: 1,
      explanation: 'Synthesizing means integrating information from multiple sources into a coherent, original understanding.',
    },
  ],

  // ─── GRADE 8 (Fire Zone) ─────────────────────────────────────────────
  grade8: [
    {
      passage: 'Scholars debate whether Shakespeare actually wrote the plays attributed to him, citing inconsistencies in education level and biographical records.',
      question: 'Which statement would best serve as a thesis for an argumentative essay on this topic?',
      options: ['Shakespeare wrote some famous plays.', 'While attribution debates exist, substantial historical evidence supports Shakespeare\'s authorship.', 'Nobody knows who really wrote Shakespeare\'s plays.', 'Scholars have studied Shakespeare for many years.'],
      correct_index: 1,
      explanation: 'A strong thesis takes a clear, defensible position and signals what the essay will argue.',
    },
    {
      passage: 'The author builds her argument by first acknowledging the strongest opposing claim, then systematically dismantling it with statistics and expert testimony.',
      question: 'How does the author structure her argument?',
      options: ['She ignores opposing views', 'She presents only her own opinion without evidence', 'She addresses and refutes the counterargument using evidence', 'She tells a personal story to prove her point'],
      correct_index: 2,
      explanation: 'Acknowledging then refuting a counterargument is a sophisticated argumentative structure.',
    },
    {
      question: 'What does it mean to "analyze" a text rather than just "summarize" it?',
      options: ['Retell what happened in order', 'Examine how and why the text works, including author choices and their effects', 'List all characters and events', 'Define unfamiliar words'],
      correct_index: 1,
      explanation: 'Analysis goes beyond retelling — it examines the author\'s craft, choices, and their impact on meaning.',
    },
    {
      passage: '"It was the best of times, it was the worst of times" — Dickens opens his novel with deliberate contradiction to capture a world of extreme inequality.',
      question: 'What literary device does Dickens use in this opening?',
      options: ['Simile', 'Alliteration', 'Juxtaposition', 'Hyperbole'],
      correct_index: 2,
      explanation: 'Juxtaposition places contrasting ideas side by side to highlight their differences.',
    },
    {
      question: 'What is the difference between "deductive" and "inductive" reasoning?',
      options: ['They are the same', 'Deductive starts with a general principle to reach a specific conclusion; inductive builds a general conclusion from specific examples', 'Inductive is always incorrect', 'Deductive uses evidence; inductive uses opinion'],
      correct_index: 1,
      explanation: 'Deductive reasoning moves from general to specific; inductive moves from specific examples to a general conclusion.',
    },
    {
      passage: 'Throughout the novel, Gatsby\'s green light represents more than just a color — it embodies the American Dream itself: always visible, always just out of reach.',
      question: 'What does the author suggest about the American Dream through this symbol?',
      options: ['It is easily achieved', 'It is a false idea with no value', 'It is a tantalizing but ultimately unreachable ideal', 'It is only meaningful for the wealthy'],
      correct_index: 2,
      explanation: '"Always visible, always just out of reach" suggests the American Dream is enticing but perpetually unattainable.',
    },
    {
      question: 'What does "ethos" refer to in persuasive writing?',
      options: ['Emotional appeal to the reader', 'The use of statistics and facts', 'The credibility and character of the author or speaker', 'The logical structure of an argument'],
      correct_index: 2,
      explanation: 'Ethos is the ethical appeal — it establishes the speaker\'s trustworthiness and expertise.',
    },
    {
      passage: 'Despite promising economic growth, the policy disproportionately burdened low-income communities while benefiting those already wealthy.',
      question: 'What implicit argument is the author making?',
      options: ['Economic growth is always good', 'The policy was fair to all groups', 'Policies should be evaluated by who they harm and who they help', 'Low-income communities should not receive benefits'],
      correct_index: 2,
      explanation: 'By highlighting unequal burdens, the author implicitly argues that equity must be considered in policy evaluation.',
    },
    {
      question: 'What is "syntax" in literary analysis?',
      options: ['The meaning of words', 'The way sentences are structured and arranged', 'The themes of a work', 'The characters in a story'],
      correct_index: 1,
      explanation: 'Syntax refers to sentence structure — how words are arranged and how that arrangement affects meaning.',
    },
    {
      passage: 'The narrator describes the war as "a great game," yet his descriptions of blood, loss, and grief contradict this characterization entirely.',
      question: 'What literary technique does the author use here?',
      options: ['Simile', 'Verbal irony', 'Flashback', 'Foreshadowing'],
      correct_index: 1,
      explanation: 'Verbal irony occurs when the stated meaning contradicts the actual meaning — calling a horrific war "a great game" is bitterly ironic.',
    },
    {
      question: 'What is the purpose of an "annotated bibliography"?',
      options: ['To list sources alphabetically without comment', 'To provide a list of sources with brief summaries and evaluations of each', 'To quote directly from each source', 'To rank sources by quality'],
      correct_index: 1,
      explanation: 'An annotated bibliography lists sources and includes brief summaries and evaluations of their relevance and credibility.',
    },
    {
      passage: 'The poet uses short, fragmented sentences in the final stanza, mirroring the subject\'s psychological breakdown.',
      question: 'What does this example demonstrate about the relationship between form and content?',
      options: ['Form and content are unrelated', 'The way a poem is written can reflect and reinforce its meaning', 'Short sentences are always better in poetry', 'The subject of the poem is not important'],
      correct_index: 1,
      explanation: 'When form (sentence structure) mirrors content (psychological breakdown), they work together to deepen meaning.',
    },
    {
      question: 'In research writing, what is "plagiarism"?',
      options: ['Citing too many sources', 'Using another person\'s words or ideas without proper attribution', 'Writing a very long essay', 'Including a bibliography'],
      correct_index: 1,
      explanation: 'Plagiarism is presenting someone else\'s work as your own without credit — it is a serious academic offense.',
    },
    {
      passage: 'Critics praised the novel\'s unflinching portrayal of systemic inequality. The author never preaches; she simply shows, leaving readers to draw their own conclusions.',
      question: 'What technique does the author use to convey her message?',
      options: ['Direct moralizing', '"Show don\'t tell" — revealing truth through depiction rather than explicit statement', 'Exaggeration for comic effect', 'Interrupting the narrative with essays'],
      correct_index: 1,
      explanation: '"Show don\'t tell" lets imagery and events communicate the theme without the author stating it outright.',
    },
    {
      question: 'What does "objectivity" mean in nonfiction and research writing?',
      options: ['Strongly favoring one side', 'Presenting information fairly without personal bias', 'Using only emotional language', 'Writing only about your own experiences'],
      correct_index: 1,
      explanation: 'Objectivity means presenting information based on evidence rather than personal feelings or prejudice.',
    },
  ],

  // ─── UNDERGROUND (mixed/general ELA review) ──────────────────────────
  underground: [
    {
      question: 'What is a "genre" in literature?',
      options: ['The length of a book', 'A category of literature with shared characteristics', 'The name of the author', 'The number of chapters'],
      correct_index: 1,
      explanation: 'Genre is a category — like mystery, fantasy, or nonfiction — defined by shared elements.',
    },
    {
      passage: 'The knight rode into the dark forest. Strange sounds echoed around him, but he pressed forward, sword in hand.',
      question: 'What is the mood of this passage?',
      options: ['Joyful', 'Tense and suspenseful', 'Peaceful', 'Funny'],
      correct_index: 1,
      explanation: 'Details like "dark forest," "strange sounds," and a drawn sword create suspense.',
    },
    {
      question: 'What does the word "protagonist" mean?',
      options: ['The villain of the story', 'The main character of a story', 'The narrator of a story', 'The author of a story'],
      correct_index: 1,
      explanation: 'The protagonist is the main character — usually the hero — whose story we follow.',
    },
    {
      question: 'What is "foreshadowing"?',
      options: ['Describing a shadow in a story', 'A flashback to earlier events', 'Hints that suggest what might happen later in the story', 'A type of poem'],
      correct_index: 2,
      explanation: 'Foreshadowing plants early clues that hint at future events in the narrative.',
    },
    {
      passage: 'The old clock on the wall had stopped at midnight ten years ago. No one ever fixed it. Some said it didn\'t matter. Others weren\'t so sure.',
      question: 'What literary device might the stopped clock represent?',
      options: ['Simile', 'Symbolism', 'Alliteration', 'Hyperbole'],
      correct_index: 1,
      explanation: 'An object that carries deeper meaning beyond its literal function — like a stopped clock representing frozen time — is symbolism.',
    },
    {
      question: 'What is the "climax" of a story?',
      options: ['The very beginning of the story', 'The turning point of greatest tension', 'The resolution of the conflict', 'The description of the setting'],
      correct_index: 1,
      explanation: 'The climax is the peak moment of tension — the turning point from which the story begins to resolve.',
    },
    {
      question: 'What is the difference between "fiction" and "nonfiction"?',
      options: ['Fiction is true; nonfiction is made up', 'Fiction is made up; nonfiction is based on real facts', 'They are the same', 'Nonfiction is always shorter'],
      correct_index: 1,
      explanation: 'Fiction is imaginary; nonfiction is based on real events, people, and facts.',
    },
    {
      passage: 'Maya knew something was wrong the moment she saw the lights were on. She had turned them off before leaving.',
      question: 'What does this passage hint at using foreshadowing?',
      options: ['Maya forgot to pay her electricity bill', 'Someone may have entered Maya\'s home', 'Maya is afraid of the dark', 'The lights were broken'],
      correct_index: 1,
      explanation: 'The lit lights — when she left them off — suggest someone has been in her home, building suspense.',
    },
    {
      question: 'What does "antagonist" mean?',
      options: ['The main hero of the story', 'The character or force that opposes the protagonist', 'The narrator of the story', 'The character who helps the hero'],
      correct_index: 1,
      explanation: 'The antagonist creates conflict by opposing the protagonist\'s goals.',
    },
    {
      question: 'What is a "stanza" in poetry?',
      options: ['A rhyming word pair', 'A group of lines forming a unit in a poem, like a paragraph in prose', 'The title of a poem', 'The rhythm of a poem'],
      correct_index: 1,
      explanation: 'A stanza is a grouped set of lines in a poem, similar to a paragraph in prose.',
    },
    {
      passage: 'The general walked slowly through the ruins of what had been a great city. He said nothing. There was nothing to say.',
      question: 'What emotion does the passage most strongly convey?',
      options: ['Excitement', 'Grief and loss', 'Anger', 'Pride'],
      correct_index: 1,
      explanation: 'Walking silently through ruins suggests profound sorrow and loss — not anger or pride.',
    },
    {
      question: 'What does "inference" mean in reading?',
      options: ['Copying directly from the text', 'A conclusion drawn from clues and prior knowledge, not stated outright', 'Summarizing the main events', 'Defining vocabulary words'],
      correct_index: 1,
      explanation: 'An inference is a logical conclusion made from text clues and what you already know.',
    },
    {
      question: 'What is "personification"?',
      options: ['Comparing two things using "like" or "as"', 'Giving human qualities or actions to non-human things', 'Exaggerating for effect', 'Repeating the same sound'],
      correct_index: 1,
      explanation: 'Personification attributes human characteristics to animals, objects, or abstract concepts.',
    },
    {
      passage: 'Every morning, the sun climbed lazily over the hills, as if reluctant to begin another day.',
      question: 'What literary device is used in this sentence?',
      options: ['Simile', 'Hyperbole', 'Personification', 'Alliteration'],
      correct_index: 2,
      explanation: 'The sun is given human qualities — being "lazy" and "reluctant" — which is personification.',
    },
    {
      question: 'What is a "theme" in literature?',
      options: ['The title of the book', 'The setting of the story', 'A central message or life lesson conveyed by the story', 'A list of events in the story'],
      correct_index: 2,
      explanation: 'Theme is the deeper message or universal truth an author communicates through the story.',
    },
  ],
};

/**
 * Get a shuffled list of questions for a given zone and grade.
 * Falls back through grades if needed.
 */
export function getQuestionsForZone(zoneId, grade) {
  const gradeKey = `grade${grade}`;
  let pool = Q[gradeKey] || Q[zoneId] || Q.underground;

  // For underground zone, always use underground pool
  if (zoneId === 'underground') pool = Q.underground;

  // Shuffle and return
  return [...pool].sort(() => Math.random() - 0.5);
}
